<?php

declare(strict_types=1);

namespace Automattic\BlocksEngine\FigmaTransformer\Html;

/**
 * Resolves source font families to emittable font CSS.
 *
 * Two resolution sources, in priority order:
 *  1. Operator-supplied `font_css` passthrough (overrides everything).
 *  2. Well-known web fonts available from the Google Fonts CDN, emitted as a
 *     weight-aware `@import` that pulls real `@font-face` rules.
 *
 * Web-safe families need no CSS. Anything else is reported as unresolved so an
 * operator can supply the missing font, keeping the font-coverage diagnostic
 * actionable rather than a bare count.
 */
final class FontResolver
{
    /**
     * Lazy-load the generated Google Fonts lookup.
     *
     * The lookup file is generated by scripts/generate-google-fonts.php from
     * the public Google Fonts metadata endpoint. Regenerate with:
     *   php figma-transformer/scripts/generate-google-fonts.php
     *
     * @return array<string, array{family: string, generic: string}>
     */
    private static function googleFonts(): array
    {
        static $fonts = null;
        if ( null === $fonts ) {
            $fonts = require __DIR__ . '/generated/google-fonts.php';
        }
        return $fonts;
    }

    /**
     * Web-safe families that render correctly without any emitted font CSS.
     *
     * @var array<string, string>
     */
    private const WEB_SAFE = array(
        'arial'           => 'sans-serif',
        'helvetica'       => 'sans-serif',
        'tahoma'          => 'sans-serif',
        'trebuchet ms'    => 'sans-serif',
        'verdana'         => 'sans-serif',
        'courier'         => 'monospace',
        'courier new'     => 'monospace',
        'georgia'         => 'serif',
        'times'           => 'serif',
        'times new roman' => 'serif',
        'monospace'       => 'monospace',
        'sans-serif'      => 'sans-serif',
        'serif'           => 'serif',
    );

    /**
     * Resolve font usage into emittable font CSS plus an actionable coverage
     * report.
     *
     * @param array<int, array<string, mixed>> $fontUsage Font usage entries
     *        (family/weights/text_node_count), as produced by the emitter.
     * @param string $operatorFontCss Operator-supplied `font_css` override.
     * @return array{
     *     css: string,
     *     operator_supplied: bool,
     *     resolved_families: array<int, string>,
     *     unresolved_families: array<int, string>,
     *     cdn_families: array<int, string>,
     *     coverage: array<int, array<string, mixed>>
     * }
     */
    public function resolve(array $fontUsage, string $operatorFontCss = ''): array
    {
        $operatorSupplied = '' !== trim($operatorFontCss);
        $coverage = array();
        $resolved = array();
        $unresolved = array();
        $cdnFamilies = array();

        foreach ( $fontUsage as $usage ) {
            if ( ! is_array($usage) ) {
                continue;
            }

            $family = $this->primaryFamily((string) ($usage['family'] ?? ''));
            if ( '' === $family ) {
                continue;
            }

            $key = strtolower($family);
            $weights = $this->normalizeWeights(is_array($usage['weights'] ?? null) ? $usage['weights'] : array());

            if ( $operatorSupplied ) {
                $resolution = 'operator_supplied';
            } elseif ( isset(self::WEB_SAFE[$key]) ) {
                $resolution = 'web_safe';
            } elseif ( isset(self::googleFonts()[$key]) ) {
                $resolution = 'cdn_google_fonts';
                $canonical = self::googleFonts()[$key]['family'];
                $cdnFamilies[$canonical] = $this->normalizeWeights(array_merge($cdnFamilies[$canonical] ?? array(), $weights));
            } else {
                $resolution = 'unresolved';
            }

            $isResolved = 'unresolved' !== $resolution;
            if ( $isResolved ) {
                $resolved[] = $family;
            } else {
                $unresolved[] = $family;
            }

            $entry = array(
                'family'              => $family,
                'weights'             => $weights,
                'text_node_count'     => (int) ($usage['text_node_count'] ?? 0),
                'resolution'          => $resolution,
                'resolved'            => $isResolved,
                'needs_operator_font' => 'unresolved' === $resolution,
                'fallback_stack'      => $this->fallbackStack($family),
            );
            if ( 'cdn_google_fonts' === $resolution ) {
                $entry['source_url'] = $this->googleFontUrl(self::googleFonts()[$key]['family'], $weights);
            }
            $coverage[] = $entry;
        }

        $css = $operatorSupplied ? trim($operatorFontCss) : $this->cdnImportCss($cdnFamilies);

        return array(
            'css'                 => $css,
            'operator_supplied'   => $operatorSupplied,
            'resolved_families'   => array_values(array_unique($resolved)),
            'unresolved_families' => array_values(array_unique($unresolved)),
            'cdn_families'        => array_keys($cdnFamilies),
            'coverage'            => $coverage,
        );
    }

    /**
     * Build a CSS font-family stack for a family name, with a sane generic
     * fallback so the browser degrades to the right generic family if the
     * resolved font fails to load.
     */
    public function fallbackStack(string $family): string
    {
        $family = $this->primaryFamily($family);
        if ( '' === $family ) {
            return 'sans-serif';
        }

        $generic = $this->genericFor($family);
        if ( strtolower($family) === $generic ) {
            return $generic;
        }

        return '"' . str_replace(array('\\', '"'), array('\\\\', '\\"'), $family) . '", ' . $generic;
    }

    private function genericFor(string $family): string
    {
        $key = strtolower($family);
        if ( isset(self::WEB_SAFE[$key]) ) {
            return self::WEB_SAFE[$key];
        }
        if ( isset(self::googleFonts()[$key]) ) {
            return self::googleFonts()[$key]['generic'];
        }
        if ( str_contains($key, 'mono') ) {
            return 'monospace';
        }
        if ( str_contains($key, 'serif') && ! str_contains($key, 'sans') ) {
            return 'serif';
        }

        return 'sans-serif';
    }

    /**
     * @param array<string, array<int, int>> $cdnFamilies Canonical family => weights.
     */
    private function cdnImportCss(array $cdnFamilies): string
    {
        if ( empty($cdnFamilies) ) {
            return '';
        }

        ksort($cdnFamilies, SORT_NATURAL | SORT_FLAG_CASE);
        $specs = array();
        foreach ( $cdnFamilies as $family => $weights ) {
            $specs[] = 'family=' . $this->googleFontSpec((string) $family, $weights);
        }

        $url = 'https://fonts.googleapis.com/css2?' . implode('&', $specs) . '&display=swap';

        return "/* Figma Transformer: source web fonts resolved via Google Fonts CDN */\n@import url('" . $url . "');";
    }

    /**
     * @param array<int, int> $weights
     */
    private function googleFontUrl(string $family, array $weights): string
    {
        return 'https://fonts.googleapis.com/css2?family=' . $this->googleFontSpec($family, $weights) . '&display=swap';
    }

    /**
     * @param array<int, int> $weights
     */
    private function googleFontSpec(string $family, array $weights): string
    {
        $spec = str_replace(' ', '+', $family);
        $weights = $this->normalizeWeights($weights);
        if ( ! empty($weights) ) {
            $spec .= ':wght@' . implode(';', $weights);
        }

        return $spec;
    }

    /**
     * Clamp weights to the standard 100-900 axis so Google Fonts css2 accepts
     * them, de-duplicated and sorted ascending.
     *
     * @param array<int, mixed> $weights
     * @return array<int, int>
     */
    private function normalizeWeights(array $weights): array
    {
        $normalized = array();
        foreach ( $weights as $weight ) {
            if ( ! is_numeric($weight) ) {
                continue;
            }
            $rounded = (int) ( round((float) $weight / 100.0) * 100 );
            $rounded = max(100, min(900, $rounded));
            $normalized[$rounded] = true;
        }

        $values = array_keys($normalized);
        sort($values, SORT_NUMERIC);

        return $values;
    }

    private function primaryFamily(string $value): string
    {
        $first = explode(',', $value, 2)[0];

        return trim($first, " \t\n\r\0\x0B\"'");
    }
}
